### ISSUE TITLE
docfx command fails on Windows machine

### ISSUE THREAD

**Issue by cartermp** [dotnet/core-docs#149]
I installed docfx under dnx as per here: http://aspnet.github.io/docfx/tutorial/docfx_getting_started.html#use-docfx-under-dnx

```
> cd docs
> docfx build
```

Outputs:

```
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Framework.ApplicationHost' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Framework.ApplicationHost'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Microsoft.Dnx.Runtime.Loader.LoadContext.Load(AssemblyName assemblyName)
   at Microsoft.Dnx.Host.Bootstrapper.RunAsync(List`1 args, IRuntimeEnvironment env, String appBase, FrameworkName targetFramework)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.ExecuteAsync(String[] args, BootstrapperContext bootstrapperContext)
   at Microsoft.Dnx.Host.RuntimeBootstrapper.Execute(String[] args, BootstrapperContext bootstrapperContext)

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
```

/cc @blackdwarf

**Comment by blackdwarf** [comment]
Try it with the full framework. If it repros, come back here again. (Take 2 aspirins and call me in the morning.)

@pengbian can we update the instructions so people know they need to use clr and mono and not coreclr?

**Comment by cartermp** [comment]
It repros:

```
> dnvm list
Active Version         Runtime Architecture OperatingSystem Alias
------ -------         ------- ------------ --------------- -----
       1.0.0-beta5     clr     x64          win
       1.0.0-beta5     clr     x86          win
       1.0.0-beta5     coreclr x64          win
       1.0.0-beta5     coreclr x86          win
       1.0.0-rc1-16202 clr     x86          win             default
  *    1.0.0-rc1-final clr     x86          win
       1.0.0-rc1-final coreclr x64          win
```

Same exception.

**Comment by blackdwarf** [comment]
@chenkennt @pengbian assuming  this is the wrong version, I guess, we need to update the docs to point to the actual version that works.

@cartermp try to uninstall docfx and then reinstall using `dnu commands install docfx 0.3.11-alpha-9-gdaed198`.

**Comment by cartermp** [comment]
@blackdwarf That seemed to work.

New problem!  Not all styling is being applied.  Tried in Chrome and Edge.

```
> docfx build
> docfx serve _site
```

Logs in chrome:

```
Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/styles/docfx.css Failed to load resource: the server responded with a status of 404 (Not Found)
main.js:68 hello
http://localhost:8080/styles/docfx.vendor.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/styles/docfx.css Failed to load resource: the server responded with a status of 404 (Not Found)
main.js:68 hello
http://localhost:8080/styles/docfx.vendor.css Failed to load resource: the server responded with a status of 404 (Not Found)
http://localhost:8080/styles/docfx.css Failed to load resource: the server responded with a status of 404 (Not Found)
```

**Comment by chenkennt** [comment]
We have pushed a new version of docfx, please reinstall (no need to specify version now) and try rebuild the doc.

**Comment by cartermp** [comment]
Thanks @chenkennt! I got the latest version through DNX and it all built.  Styles are now also applied.

One thing I did notice was logging "hello" to the console twice from `docfx.js:68`.  Is this going to eventually be removed?

**Comment by cartermp** [comment]
Got this resolved.
